VIMNetworking/Model/VIMPictureCollection.m

Changes `abs()` to `fabs()` in order to resolved Xcode 6.3 errors.

Update for xcode 6.3

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadSessionManager.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m
VIMNetworking/Networking/VimeoClient/VIMRequestOperationManager.m

Modified task completion logic so that task.error is set before task.state, specifically so that error can be read during KVO on failure_state.
https://vimean.atlassian.net/browse/VIM-2314

VIM-2314: Upload Quota Exceptions

---

VIMNetworking/Networking/VimeoClient/VIMSession.m

This branch cleans up a few rough edges around the recent accounts work. 
- Users who log in to previous app version, upgrade to new version, and logout. They lack a cached client credentials account. This fully logs them out and fetches new cc account. 
- A few other things... :)

Rough edges

---

VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m

Comments from marc:
Alfie,
was helping today Mark Essel with refactoring this code, and notice the following:
we can discuss but I think these safety are needed I feel. Look at <<<<< inserted this
maybe resume case is debatable because it is paused anyway...
- (void)suspend
{
if (self.isSuspended)
{
return;
}
self.suspended = YES;
dispatch_async(_tasksQueue, ^{ <<<<<< inserted this:
if (self.currentTask)
{
[self.currentTask suspend];
}
[self save];
}
}
- (void)resume
{
if (!self.isSuspended)
{
return;
}
self.suspended = NO;
dispatch_async(_tasksQueue, ^{ <<<<<< inserted this:
[self save];
dispatch_async(_tasksQueue, ^{
[self restart];
});
}
}
- (VIMTask *)taskForIdentifier:(NSString *)identifier
{
if (!identifier)
{
return nil;
}
<<<<<< should line below not be part of …

Task Queue Thread Safety 

---

VIMNetworking/Networking/VimeoClient/VIMClient.m
VIMNetworking/Networking/VimeoClient/VIMSession.m

@alfiehanssen This branch fixes two issues I came across with the new VIMClient structure when I was fixing a bug where deeplinks would not launch properly.
1.  in VIMSession's -buildClient, initWithBaseURL is used to create VIMClient, meaning that -init was never actually used on that class, and VIMRetryManager was always null.  I modified the VIMClient initializer to correctly override the superclass initializer.
2.  When the base URL changed method of VIMSession is called (every time /configs loads, at minimum), VIMClient was always recreated anew regardless of whether it was necessary or not.  This caused issues with requests that were already in progress because the weakSelf of VIMClient in those completion blocks became nil, so naturally any further action requested therein was …

some fixes to VIMClient regarding initialization and base URL swapping

---

README.md
VIMNetworking/Networking/VimeoClient/VIMClient.h
VIMNetworking/Networking/VimeoClient/VIMClient.m
VIMNetworking/Networking/VimeoClient/VIMSessionConfiguration.h
VIMNetworking/Networking/VimeoClient/VIMSessionConfiguration.m

We can now more easily make simple requests with an existing token without using local sessions.
```objective-c
self.client = [[VIMClient alloc] initWithDefaultBaseURL];
self.client.delegate = self;
[self.client requestURI:@"/videos/77091919" completionBlock:^(VIMServerResponse *response, NSError *error)
{
id JSONObject = response.result;
NSLog(@"JSONObject: %@", JSONObject);
}];
- (NSString *)authorizationHeaderValue:(nonnull VIMRequestOperationManager *)operationManager
{
return [NSString stringWithFormat:@"Bearer <TOKEN>"];
}
```

Convenience Initializer

---

VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMCreateTicketTask.m

We may have not been checking for certain upfront create errors, in which case they would be reported as upload_link_secure missing errors.
https://vimean.atlassian.net/browse/VIM-2724

Additional Error Check in Upload CREATE Task

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

Crash fix for observers not being removed before videoAsset is deallocated.
https://vimean.atlassian.net/browse/VIM-2749
https://rink.hockeyapp.net/manage/apps/106799/app_versions/18/crash_reasons/42764703

VIMVideoAsset KVO Crash Fix

---

VIMNetworking/Model/VIMVideoFile.m

A nil expiration date evaluates to NSOrderedSame (seems counterintuitive to me), removing NSOrderedSame from the check. 
https://vimean.atlassian.net/browse/VIM-2845

Potential fix for issue where expires check always fails

---

VIMNetworking/Model/VIMVideo.m

https://vimean.atlassian.net/browse/VIM-2845
This specifies locale whenever we're creating a date formatter.

VIM-2845: Fix timezone format issue

---

README.md
VIMNetworking/Networking/VimeoClient/VIMSessionConfiguration.m

Keychain access group is optional but the session configuration isValid method was treating it as if it was non optional. Fixes issue #138.

Keychain Fix

---

README.md
VIMNetworking.podspec
VIMNetworking/Networking/VimeoClient/VIMSession.m
VIMNetworking/Networking/VimeoClient/VIMSessionConfiguration.m

This notification was being posted even if the "new" account was the same as the "old" account. Now it's only being posted if the accounts' auth tokens differ.
https://vimean.atlassian.net/browse/VIM-2934

VIM-2934: Only posting accountDidChange notification when the account actually changed!

---

VIMNetworking/Model/VIMUser.h
VIMNetworking/Model/VIMUser.m
VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m

https://vimean.atlassian.net/browse/VIM-3241
This PR exposes the account string on the user object and adds a new enum value to the video status enum.

VIM-3241: Model adjustments for upload

---

VIMNetworking/Networking/VimeoClient/VIMSessionManager.h
VIMNetworking/Networking/VimeoClient/VIMSessionManager.m

[VIM-3308](https://vimean.atlassian.net/browse/VIM-3308)
This ticket is part of building the new download system. This PR is a side effect of that work.
We're deprecating the old download system that relied on a few download-specific methods here. Removed those methods. Don't need 'em anymore.
Aint no test.

VIM-3308: Remove unused download-specific methods

---

VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m

[VIM-3591](https://vimean.atlassian.net/browse/VIM-3591)
Add support for the new "transcode_starting" state for clip object "status".
Added this to VIMNetworking and the app.
You'd have to refresh a just uploaded video object to see this. Might be difficult.

VIM-3591: Added support for the new transcode_starting state

---

VIMNetworking/Keychain/VIMKeychain.m
VIMNetworking/Networking/VimeoClient/VIMSession.m

Removing old extension auth logic. The app was sending out unnecessary VIMSession_AuthenticatedAccountDidChangeNotification notifications when the user was logged out after foregrounding.
Also adding a comment to weird keychain behavior that has been triggering some asserts. The problem looks like an Apple issue, but it has only been seen so far in dev.

Removing Extension Logic

---

VIMNetworking/Model/VIMPrivacy.h
VIMNetworking/Model/VIMPrivacy.m
VIMNetworking/Model/VIMVideo.h

[VIM-3712](https://vimean.atlassian.net/browse/VIM-3712)
[Companion PR](https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/775) for context
Updated model for unlisted privacy
Updated `VIMPrivacy` for unlisted privacy setting. 
Updated `VIMVideo` to receive `resourceKey` from API, useful to identify videos given uri is mutable based on privacy setting. 
Ensure params conform to correct naming convention 
Ensure `resourceKey` is accessible on a `VIMVideo` object
@huebnerob could you review and proceed with [VIM-3978](https://vimean.atlassian.net/browse/VIM-3978)? Thank you!

VIM-3712: update model for unlisted privacy

---

VIMNetworking/Model/VIMVideoPreference.h

https://vimean.atlassian.net/browse/VIM-3675
1. On desktop, set your global upload privacy setting to 'password' and save a default password 
2. Open the app and upload a video 
3. Under password, tap 'set password'
User should see their default password. They should be able to proceed to Upload without checking it.
This works with another PR, adds video password to Preferences

VIM-3675: Adds password to VIM Preferences

---

VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m

[VIM-4042](https://vimean.atlassian.net/browse/VIM-4042)
parent PR: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/860
Android is using release_time, if available, to display dates on videos and falling back on created_time
Added support to receive release_time on a video object 
NA

VIM-4042: Added Release Time to Video Object

---

VIMNetworking/Model/VIMVideo+VOD.h
VIMNetworking/Networking/VimeoClient/VIMClient.h
VIMNetworking/Networking/VimeoClient/VIMClient.m
VIMNetworking/Networking/VimeoClient/VIMJSONResponseSerializer.m

[VIM-4087](https://vimean.atlassian.net/browse/VIM-4087)
We need to access the VOD trailer URI from a VIMVideo.
Function prototype was added to `VIMVideo+VOD` header for method `vodTrailerURI` so it would be publicly accessible.
NA

VIM-4087: Load Trailers for VOD items

---

VIMNetworking/Model/VIMUser.h
VIMNetworking/Model/VIMUser.m

[VIM-4264](https://vimean.atlassian.net/browse/VIM-4264)
Make emails accessible on user object.
The emails object is received as an array of dictionaries holding "email":"emailString" key value pairs.  To make them more accessible, the email string values are grabbed and stored in the  `userEmails` array property on user object. 
See parent ticket referencing this.

VIM-4264: Add emails to user model

---

VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m
VIMNetworking/Model/VIMVideoDRMFiles.h
VIMNetworking/Model/VIMVideoDRMFiles.m
VIMNetworking/Model/VIMVideoFairPlayFile.h
VIMNetworking/Model/VIMVideoFairPlayFile.m
VIMNetworking/Model/VIMVideoLog.h
VIMNetworking/Model/VIMVideoLog.m
VIMNetworking/Model/VIMVideoPlayRepresentation.h
VIMNetworking/Model/VIMVideoPlayRepresentation.m

https://vimean.atlassian.net/browse/VIM-4411
This ticket adds the FairPlay DRM models to the video model.
Added the necessary models to the video model.
Go to the the profile for "TC Test Account" and play the "Caminandes : Llama Drama" video. Ensure that the correct video>play>drm>fairplay fields are populated.

VIM-4411: FairPlay DRM Models

---

VIMNetworking/Model/VIMUser.h
VIMNetworking/Model/VIMUser.m
VIMNetworking/Model/VIMUserBadge.h
VIMNetworking/Model/VIMUserBadge.m
VIMNetworking/Networking/VimeoClient/VIMSession.m

_original PR review comments can be found [here](https://github.com/vimeo/VIMNetworking/pull/204)_
[4306](https://vimean.atlassian.net/browse/VIM-4306)
Implement badges from the user api response and adds new badges (staff, curation, alum, etc)
Adds the new business account type tier and the badge property to VIMUser
Associated PR: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/931

VIM-4306: Add badge to response filter

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h

[VIM-4255](https://vimean.atlassian.net/browse/VIM-4255)
Add case to support new api error 
Added case to support new api error 
See associated parent PR
https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/994

VIM-4255: Serve helpful error when unverified user attempts to comment
