VIMNetworking/Networking/VimeoClient/VIMRequestSerializer.m
VIMNetworking/Networking/VimeoClient/VIMSession.m

Fixed logout bug where account credential would only be deleted upon completion of network request.

Logout Bug

---

VIMNetworking.xcodeproj/project.pbxproj
VIMNetworking/Networking/Upload/Categories/AVAsset+Filesize.h
VIMNetworking/Networking/Upload/Categories/AVAsset+Filesize.m
VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMTempFileMaker.m

https://vimean.atlassian.net/browse/VIM-2210

Added filesize check for AVURLAssets

---

VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.h
VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.h
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m
VIMNetworking/Networking/Upload/VIMTaskQueueDebugger.m

Reverts vimeo/VIMNetworking#10

Revert "Upload push"

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadSessionManager.m

https://vimean.atlassian.net/browse/VIM-2260

Added cert pinning for upload tasks

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.h
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

Returns the assets themselves from the upload queue tracker

Upload analytics

---

VIMNetworking/Networking/Upload/UploadTaskQueue/Model/VIMVideoAsset.h
VIMNetworking/Networking/Upload/UploadTaskQueue/Model/VIMVideoAsset.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTask.m

https://vimean.atlassian.net/browse/VIM-2291

RC-2 Fixes

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

https://vimean.atlassian.net/browse/VIM-2311

Ensuring that we remove KVO observers at all times

---

VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.h
VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m

Added upload success notification, moved broadcast of failure notification.

Upload Notifications

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

This PR upgrades task queue tracker to use NSUserDefaults for saving and loading its data. 
Also supports upgrade from initial upload release that used NSCache.

Queue Tracker

---

VIMNetworking/Networking/Upload/NetworkTaskQueue/VIMNetworkTaskQueue.m

https://vimean.atlassian.net/browse/VIM-2272

Better pause/resume by user handling

---

VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m

https://vimean.atlassian.net/browse/VIM-2411

TaskQueue Thread Safety Measures

---

Pods/Pods.xcodeproj/project.pbxproj
VIMNetworking/External/AMHKeychain/KeychainUtility.m

https://vimean.atlassian.net/browse/VIM-2266

Potential fix for auto logout issue

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTask.m

https://vimean.atlassian.net/browse/VIM-2424

Changed order of coder props, added videoMetadata to coding

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

https://rink.hockeyapp.net/manage/apps/106799/app_versions/12/crash_reasons/36908762

Task queue tracker crash protection

---

VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMTempFileMaker.m

https://vimean.atlassian.net/browse/VIM-2488

Upload Etc.

---

VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m

https://vimean.atlassian.net/browse/VIM-2527

Moved a bunch of logic from subclass into superclass

---

VIMNetworking/Networking/Auth/VIMAccountStore.h
VIMNetworking/Networking/Auth/VIMAccountStore.m
VIMNetworking/Networking/VimeoClient/VIMSession.m

Moving legacy key to be adjacent to others.
https://vimean.atlassian.net/browse/VIM-2574

Some re-org on accounts stuff

---

VIMNetworking/Networking/Reachability/VIMReachability.m
VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueue.m

https://vimean.atlassian.net/browse/VIM-2417

Posting notifications on main thread when possible

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h
VIMNetworking/Networking/Upload/Categories/NSError+VIMUpload.h
VIMNetworking/Networking/Upload/Categories/NSError+VIMUpload.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMActivateTicketTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMAddMetadataTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMCreateTicketTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMTempFileMaker.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMUploadFileTask.m

https://vimean.atlassian.net/browse/VIM-2455

Surfacing upload errors that arise due to insufficient local storage

---

VIMNetworking/Networking/Upload/NetworkTaskQueue/VIMNetworkTaskQueue.m

https://vimean.atlassian.net/browse/VIM-2563

Trying not to make cellularUploadEnabled confusing af

---

VIMNetworking/Caching/VIMCache.m
VIMNetworking/Model/VIMActivity.h
VIMNetworking/Model/VIMActivity.m
VIMNetworking/Model/VIMCategory.h
VIMNetworking/Model/VIMCategory.m
VIMNetworking/Model/VIMChannel.h
VIMNetworking/Model/VIMChannel.m
VIMNetworking/Model/VIMUser.h
VIMNetworking/Model/VIMUser.m
VIMNetworking/Model/VIMVideo.m

https://vimean.atlassian.net/browse/VIM-2613

Caching & Merging & Refresh

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.m
VIMNetworking/Networking/Upload/Categories/NSError+VIMUpload.h
VIMNetworking/Networking/Upload/Categories/NSError+VIMUpload.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMActivateTicketTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMCreateTicketTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/Subtasks/VIMUploadFileTask.m

Also this, way more crucial: 
https://vimean.atlassian.net/browse/VIM-2673
https://vimean.atlassian.net/browse/VIM-2674
https://vimean.atlassian.net/browse/VIM-2606

Fixed error domain that was miscategorized

---

VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTask.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueueTracker.m

@alfiehanssen @ghking Ready for review, see commits

Little Buggy

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h
VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.m

Some work to support reporting a standard set of attributes for any error event.
https://vimean.atlassian.net/browse/VIM-2611

VIM-2611: Error attributes reporting

---

VIMNetworking.podspec

Updates the podspec to add all authors that have contributed to this repo

Adds Pod Authors

---

VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.h
VIMNetworking/Networking/Upload/TaskQueue/VIMTaskQueue.m
VIMNetworking/Networking/Upload/UploadTaskQueue/VIMUploadTaskQueue.m

https://vimean.atlassian.net/browse/VIM-2655

Optimized cancelTask to use async instead of sync

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h
VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.m

Exposing two additional pieces of information on error category.

Error reporting

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h
VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.m
VIMNetworking/Networking/VimeoClient/VIMRequestRetryManager.m

@huebnerob @ghking 
Using this in more than one place, moved it here, better location.

Consolidated error codes

---

Podfile
VIMNetworking.podspec
VIMNetworking/Networking/VimeoClient/VIMRequestOperationManager.m

AFNetworking 2.6.0

---

VIMNetworking/Model/VIMPrivacy.h
VIMNetworking/Model/VIMPrivacy.m

In support of new video settings work

Add disabled privacy

---

VIMNetworking/Networking/VimeoClient/VIMSessionManager.h
VIMNetworking/Networking/VimeoClient/VIMSessionManager.m

Moved methods that were in VIMUpload onto the VIMSessionManager object.
https://vimean.atlassian.net/browse/VIM-3215

VIM-3215: New Upload Integration

---

VIMNetworking/Model/VIMCategory.h
VIMNetworking/Model/VIMCategory.m
VIMNetworking/Model/VIMChannel.h
VIMNetworking/Networking/VimeoClient/VIMClient.h
VIMNetworking/Networking/VimeoClient/VIMClient.m

Helper methods for channels and categories

Channels and Categories

---

VIMNetworking/Model/VIMVideo.h
VIMNetworking/Model/VIMVideo.m

<b>Ticket Number</b>
https://vimean.atlassian.net/projects/VIM/issues/VIM-3674
<b>Ticket Summary</b>
Request to show current password for password protected video in the textfield of the alert displayed when changing the current password.
<b>Implementation Summary</b>
Adds password property to VIMVideo

VIM-3674: Adds password property for VIMVideo

---

Podfile
VIMNetworking.podspec

[TICKET_NUMBER](https://vimean.atlassian.net/browse/TICKET_NUMBER)
A brief but thorough description of the ticket.
A brief but thorough description of the changes put in place to address the ticket.
Detailed *list* of what to test and how to test it. Including all edge cases.

6.0.1 -> 6.0.2

---

VIMNetworking/Networking/VimeoClient/VIMClient.h
VIMNetworking/Networking/VimeoClient/VIMClient.m

https://vimean.atlassian.net/browse/VIM-3869
Refactor our action controllers to use something more generic
see https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/739
TBD

Action controllers refactor

---

VIMNetworking/Networking/VimeoClient/VIMRequestOperationManager.h

See https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/821

VIM-4079: Camera Roll Prework

---

VIMNetworking/Networking/VimeoClient/VIMClient.h
VIMNetworking/Networking/VimeoClient/VIMClient.m

https://vimean.atlassian.net/browse/VIM-4069
This ticket adds convenience method for requesting VOD films and series.
Added a new method for requesting VOD items.
Associated PR: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/877

VIM-4069: VOD Deep Links

---

VIMNetworking/Networking/ErrorReporting/NSError+VIMNetworking.h

Adding some error codes.
Associated PR: https://github.vimeows.com/MobileApps/Vimeo-iOS/pull/958

VIM-4419: DRM errors
